config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :categories
  end

  resources :posts do
    resources :comments
  end

  get '/:short_url' => 'posts#redirect'
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :post, dependent: :restrict_with_error
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content

  belongs_to :post, counter_cache: :comments_count
  belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content
  belongs_to :user
  belongs_to :category
  belongs_to :region
  belongs_to :province
  belongs_to :city
  has_many :comments, dependent: :restrict_with_error

  mount_uploader :image, ImageUploader

  before_create  :generate_address
  after_create :generate_unique_number

  def generate_unique_number
    # loop do
    #   @short = rand(0..9999).to_s.rjust(4, '0')
    #   break unless Post.exists?(short_url: @short)
    # end
    # self.short_url = @short
    self.update(short_url: self.id.to_s.rjust(4, '0'))  #try to use id instead
  end

  def generate_address
    user_address = "#{self.region.name}, #{self.province.name}, #{self.city.name}"
    self.address = user_address
  end

end

app/models/province.rb
class Province < ApplicationRecord
  has_many :city
  has_many :posts
  belongs_to :region
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :provinces
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments

  def client?
    role == 'client'
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :check_admin
    before_action :set_category, only: [:edit, :update, :destroy]


    def index
      @categories= Category.all
    end

    def new
      @category = Category.new
    end

    def edit; end

    def update
      if @category.update(category_params)
        redirect_to admin_categories_path
      else
        render :edit
      end
    end

    def destroy
      unless @category.destroy
        flash[:alert] = "this disaster type is currently in use in a post"
      end
      redirect_to admin_categories_path
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path
      else
        render :new
      end
    end

    def check_admin
      unless current_user.admin?
        flash[:notice] = "You do not have permission"
        redirect_to posts_path
      end
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post
  before_action :set_own_comment, only: [:edit, :update, :destroy]


  def index
    @comments = @post.comments.includes(:user)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to post_comments_path(@post, @comment)
    else
      render :edit
    end
  end

  def destroy
    if @comment.destroy
      redirect_to post_comments_path(@post)
    end
  end

  private

  def set_own_comment
    @comment = current_user.comments.find_by_id(params[:id])
    if @comment.nil?
      flash[:alert] = 'this post not belongs_to you or not exists'
      redirect_to post_comments_path
    end
  end

  def set_post
    @post = Post.find_by_id(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post, only: :show
  before_action :set_own_post, only: [:edit, :update, :destroy]
  require 'open-uri'

  def index
    @page = params[:page] || 1
    @per = 5
    @next_index = (@page.to_i*5)-5

    if params[:filter_by]== "user"
      @posts = current_user.posts.order(comments_count: :desc).includes(:user, :comments).page(params[:page]).per(@per)
    elsif params[:filter_by]== "category"
      @posts = Post.where('category_id=?', params[:id]).order(comments_count: :desc).includes(:user, :comments).page(params[:page]).per(@per)
    else
      @posts = Post.order(comments_count: :desc).includes(:user, :comments).page(params[:page]).per(@per)
    end
    @categories = Category.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def redirect
    @short = params[:short_url]
    @url = Post.find_by(short_url: @short)
    if @url.nil? #if 404
      content_not_found
    else
      redirect_to post_path(@url)
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def show; end

  def destroy
    unless @post.destroy
      flash[:alert] = "this post has comments you can't delete it"
    end
    redirect_to posts_path
  end


  private

  def set_own_post
    @post = current_user.posts.find_by_id(params[:id])
    if @post.nil?
      flash[:alert] = 'this post not belongs_to you or not exists'
      redirect_to posts_path
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :region_id, :province_id, :city_id, :image)
  end

  def set_post
    @post = Post.find_by_id(params[:id])
  end

  def content_not_found
    render :file => "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/edit.html.erb
<h1>Edit Disaster id: <%= @category.id %></h1>
<%= link_to 'back', admin_categories_path, class: 'btn btn-danger' %>
<%= form_for @category, url: admin_category_path(@category), method: :patch do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit 'Update', class: 'btn btn-success' %>
<% end %>

app/views/admin/categories/index.html.erb
<%#= link_to 'Back to post', posts_path, class: 'btn btn-warning'%>
<%= link_to "Logout", destroy_user_session_path, :method => :delete, class:"btn btn-warning float-right" %>

<h1>Disaster type</h1>
<table class="table table-striped table-hover">
  <thead>
  <th>Id</th>
  <th>Type</th>
  <th>Action</th>
  </thead>
  <tbody>
  <% @categories&.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= category.name%></td>
      <td><%= link_to 'edit', edit_admin_category_path(category), class: 'btn btn-warning' %>
        <%= button_to "delete", admin_category_path(category), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New', new_admin_category_path, class: 'btn btn-success' %>

app/views/admin/categories/new.html.erb
<h1>New Disaster type<%= @category.id %></h1>
<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<%= form_for @category, url: admin_categories_path(@category), method: :post do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>
<%= link_to 'back', admin_categories_path %>

app/views/comments/edit.html.erb
<h1>Edit Post id: <%= @post.id %>, Comment ID:<%= @comment.id %></h1>

<%= form_for @comment, url: post_comment_path(@post, @comment), method: :patch do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<h1><%= @post.id %></h1>
<%= link_to 'back to posts index', posts_path, class: "btn btn-danger" %>
<div class="card" style="width: 18rem;">
  <div class="card-header"><%= @post.title %></div>
  <%#= image_tag "#{request.base_url}#{@post.image.url}", class:"card-img-top" if @post.image? %>
  <div class="card-body">
    <span class="badge bg-warning">
       <%= @post.category.name %>
    </span>
    <p class="card-text"><%= @post.content %></p>
    <p class="card-text"><small class="text-muted">created by: <%= @post.user.email %></small></p>
  </div>
</div>
<%unless @comments.size.zero?%>
  <h3>Comments</h3>
  <table class="table">
    <thead>
    <th>id</th>
    <th>creator</th>
    <th>content</th>
    <th>action</th>
    </thead>
    <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.user.email %></td>
        <td><%= comment.content %></td>
        <td>
          <% if comment.user == current_user %>
            <%= link_to 'edit', edit_post_comment_path(@post, comment), class: "btn btn-warning" %>
            <%= button_to "delete", post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div>no comment to show</div>
<% end %>
<%= link_to 'new comment', new_post_comment_path(@post), class: "btn btn-success" %>

app/views/comments/new.html.erb
<h1>New comment for Post id <%= @post.id %></h1>

<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<%= form_for @comment, url: post_comments_path(@post), method: :post do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, class: 'input-field' %>
  <%= f.submit 'Post', class: 'btn btn-success' %>
<% end %>

<%= link_to 'back', post_comments_path, class: 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<% if post.errors.any? %>
  <% post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :image %>
  <%= f.file_field :image, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :category %>
  <%= f.collection_select :category_id, Category.order(:name), :id, :name, {:include_blank => true}, {class: "form-control"} %>
</div>
<div class="form-group">
  <%= f.label :region %>
  <%= f.collection_select :region_id, Region.order(:name), :id, :name, {:include_blank => true}, {class: "form-control"} %>
</div>
<div class="form-group">
  <%= f.label :province %>
  <%= f.collection_select :province_id, Province.order(:name), :id, :name, {:include_blank => true}, {class: "form-control"} %>
</div>
<div class="form-group">
  <%= f.label :city %>
  <%= f.collection_select :city_id, City.order(:name), :id, :name, {:include_blank => true}, {class: "form-control"} %>
</div>
<div class="form-group">
  <%= f.submit class: 'btn btn-success' %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post Id: <%= @post.id %></h1>
<%= link_to 'back to index', posts_path, class:"btn btn-danger" %>
<%= form_for @post, url: post_path(@post), method: :patch do |f| %>
  <%= render partial: 'form', locals: {f: f, post: @post} %>
<% end %>

app/views/posts/index.html.erb
<%= link_to 'Manage Disaster info', admin_categories_path, class: 'btn btn-warning' if current_user&.admin? %>

<%= link_to "Log Out", destroy_user_session_path, :method => :delete, class: "btn btn-warning float-right" if current_user%>
<%= link_to "Log In", new_user_session_path, class: "btn btn-success float-right" unless current_user%>
<h1>Post list</h1>

<%= link_to 'Show All', posts_path, class: "btn btn-success float-right"%>
<%= link_to 'My post', posts_path({filter_by: :user})  ,class: "btn btn-success float-right"%>
<br>
<% @categories.each do |category| %>
  <%= link_to category.name, posts_path({id: category, filter_by: :category}), class: "btn btn-success float-right"%>
<% end %>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <% if params[:filter_by]== nil %>
        <th scope="col">Rank</th>
    <% end%>
    <th scope="col">ID</th>
    <th scope="col">Creator</th>
    <th scope="col">Title</th>
    <th scope="col">Content</th>
    <th scope="col">Address</th>
    <th scope="col">Disaster</th>
    <th scope="col">Image</th>
    <th scope="col">Short URL</th>
    <th scope="col">actions</th>

  </tr>
  </thead>
  <tbody>
  <% @posts.each_with_index do |post, index| %>
    <tr>
      <% if params[:filter_by]== nil %>
        <td><%= @next_index + index + 1 %>
          <% if index < 3 && @page == 1%>
            <br>
            <span class="badge bg-danger">
                HOT
            </span>
          <% end %>
        </td>
      <% end %>
      <td><%= post.id %></td>
      <td><%= post.user.email %></td>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= post.address %></td>
      <td><%= post.category.name %></td>
      <td><%= image_tag "#{request.base_url}/#{post.image.url}" if post.image? %></td>
      <td><%= link_to "#{request.base_url}/#{post.short_url}", "#{request.base_url}/#{post.short_url}", target: :_self %></td>
      <td>
        <%= link_to :comments, post_comments_path(post), class: 'btn btn-info' %>
        <%= link_to "show", post_path(post), class: 'btn btn-primary' %>
        <%= link_to "edit", edit_post_path(post), class: 'btn btn-warning' if post.user == current_user %>
        <% if post.user == current_user %>
          <%= form_for post, url: post_path(post), method: :delete do |f| %>
            <%= f.submit 'delete', class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @posts , style: "display: inline;"%>
<%= link_to 'New', new_post_path, class: 'btn btn-success' %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post, url: posts_path, method: :post do |f| %>
  <%= render partial: 'form', locals: {f: f, post: @post} %>
<% end %>

app/views/posts/show.html.erb
<h1>show post id <%= @post.id %></h1>
<ul>
  <li><%= @post.title %></li>
  <li><%= @post.content %></li>
</ul>
<%= link_to 'index', posts_path %>
<%= link_to 'edit', edit_post_path(@post) %>